"""Add AnalysisReport model

Revision ID: 94bc06862481
Revises: 2222001cdfec
Create Date: 2026-08-10 02:17:49.789915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bc06862481'
down_revision: Union[str, Sequence[str], None] = '2222001cdfec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('resume_filename', sa.String(), nullable=False),
    sa.Column('jd_filename', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('full_report_data', sa.JSON(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_id'), 'analysis_reports', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_reports_user_id'), 'analysis_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_reports_user_id'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###
